@API_KEY = 4cb6df1ef97d71ce804aa322eafbcd0d
@API_URL = https://api.themoviedb.org/3

GET {{API_URL}}/discover/tv/?with_network=213&language=pt-BR&api_key={{API_KEY}}
content-type: application/json

###
